version: '3.7'
services:
  php-base:
    container_name: 'php-base'
    hostname: 'php-base'
    image: ${DOCKER_REGISTRY?}/${DOCKER_NAMESPACE?}/php-base-${ENV?}:${TAG?}
    build:
      context: '../services/php/'
      dockerfile: 'base/Dockerfile'
      args:
        - ALPINE_VERSION=${ALPINE_VERSION?}
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER?}
        - APP_GROUP_ID=${APP_GROUP_ID?}
        - APP_GROUP_NAME=${APP_GROUP_NAME?}
        - APP_USER_ID=${APP_USER_ID?}
        - APP_USER_NAME=${APP_USER_NAME?}
        - COMPOSER_VERSION=${COMPOSER_VERSION?}
        - ENV=${ENV?}
        - TARGET_PHP_VERSION=${PHP_VERSION?}
      target: ${ENV?}
    ports:
      - '5000'
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${APP_CODE_PATH_HOST}
        target: '/var/www/app'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - envx

# Docker Networks
networks:
  envx:
    driver: bridge
