#!/usr/bin/env bash

cwd=$(pwd)/;


dockerfile=${cwd}compose/docker-compose.yml;

echo "Docker building from scratch...\n";

echo "Docker compose up..."
docker-compose -f ${dockerfile} build --no-cache &&
docker-compose -f ${dockerfile} up --force-recreate --remove-orphans -d;

echo "Docker status...\n";
docker ps -a;
