CREATE TABLE `premises_type_attributes` (
`attribute_id` bigint(14) unsigned NOT NULL AUTO_INCREMENT,
`attribute_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
`attribute_ref` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
`response_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
`response_type_alt` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
`response_options` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
`response_group` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
`accepted_file_types` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
`is_mandatory` tinyint(1) DEFAULT '1',
`is_mobile_visible` tinyint(1) DEFAULT '1',
`photo_required` tinyint(1) DEFAULT '0',
`max_length` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
`ordering` int(11) DEFAULT NULL,
`date_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`created_by` int(11) DEFAULT NULL,
`last_modified` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`last_modified_by` int(11) DEFAULT NULL,
`is_active` tinyint(1) DEFAULT '1',
`premises_type_id` int(11) unsigned DEFAULT NULL,
`account_id` int(11) NOT NULL,
PRIMARY KEY (`attribute_id`),
KEY `paccount_id` (`account_id`),
KEY `premises_type_id` (`premises_type_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci