#!/bin/bash

# PHP CodeSniffer
./vendor/bin/phpcs --config-set colors 1 >> /dev/null
./vendor/bin/phpcs --config-set show_progress 1 >> /dev/null
./vendor/bin/phpcs --config-set show_warnings 1 >> /dev/null

./vendor/bin/phpcs --standard=PSR12 --parallel=4 -p app
